#!/bin/bash
#
#   FFSB test: ./tsbm <command> <test path>
#   Example  : ./tsbm testall /mnt/ceph 
###############################################################

set -e

VER="1.0.8"

MAX_FILE_SIZE="4096" # Default,4096MB,should be > 2*amount of memory size
MIN_FILE_SIZE="1024" # MB,only use for iozone

CMDS=$1
TESTPATH=$2

CURDIR=`dirname $0`
export TSBMPATH=`pwd`
BMPATH=$CURDIR/bench

function usages() {
echo -e "\e[1;31mUsage    : $0 <command> <test path> \e[0m"
echo -e "\e[1;31mCommands :
testall  : ffsb dbench iozone postmark tiobench test
ffsb     : file system perfmance tester 
bonnie   : R/W perfmance and stress tester 
iozone   : R/W perfmance and stress tester 
dbench   : file server perfmance tester 
postmark : create/delete folder perfmance tester 
tiobench : thread i/o tester 
fsstress : file system mds stress test tool 
blogbench: file system performance test tool 
rwtest   : data compare(cmp) test tool,tdfs-bench rwtest
fdtree   : file system mds data test tool 
--help   : list help page 
-h       : list help page 
\e[0m\n"
}
function alltest() {
	echo "=======================ffsb test =============================="
	$BMPATH/ffsb/ffsb.sh $TESTPATH 
	sleep 10
	echo "=======================dbench test =============================="
	$BMPATH/dbench/dbench.sh $TESTPATH 
	sleep 10
	echo "=======================iozone test =============================="
	$BMPATH/iozone/iozone.sh $TESTPATH $MIN_FILE_SIZE $MAX_FILE_SIZE
	sleep 10
	echo "=======================postmark test =============================="
	$BMPATH/postmark/postmark.sh $TESTPATH 
	sleep 10
	echo "=======================tiobench test =============================="
	$BMPATH/tiobench.sh $TESTPATH 
	echo "=======================fsstress test =============================="
	$BMPATH/fsstress.sh $TESTPATH 
	echo "=======================blogbench test =============================="
	$BMPATH/blogbench.sh $TESTPATH 
	echo "=======================fdtree test =============================="
	$BMPATH/fdtreebench.sh $TESTPATH 
}

if [ "$1" = "--help" ] || [ "$1" = "-h" ] ; then
	echo -e "\e[1;31mTransoft Benchmark Interface,version : $VER\e[0m"
	usages
	exit 0
elif [ "$1" != "rwtest" ] && [ $# != 2 ] ; then
	echo -e "\e[1;31mUsage: $0 <command> <test path> \e[0m"
	echo -e "\e[1;31mUse 'tsbm [--help | -h]' to list help info\e[0m\n"
	exit 0
fi


case $CMDS in 
testall)
alltest
;;
bonnie)
$BMPATH/bonnie++/bonnie.sh $TESTPATH $MAX_FILE_SIZE
;;
iozone)
$BMPATH/iozone/iozone.sh $TESTPATH $MIN_FILE_SIZE $MAX_FILE_SIZE
;;
tiobench)
$BMPATH/tiobench/tiobench.sh $TESTPATH 
;;
dbench)
$BMPATH/dbench/dbench.sh $TESTPATH 
;;
ffsb)
$BMPATH/ffsb/ffsb.sh $TESTPATH 
;;
postmark)
$BMPATH/postmark/postmark.sh $TESTPATH 
;;
fsstress)
$BMPATH/fsstress/fsstress.sh $TESTPATH 
;;
blogbench)
$BMPATH/blogbench/blogbench.sh $TESTPATH 
;;
rwtest)
$BMPATH/rwtest/rwtest.sh
;;
fdtree)
$BMPATH/fdtree/fdtreebench.sh   ${TESTPATH}
;;
*)
echo -e "\e[1;31mError command: $1\e[0m\n"
usages
exit 0
;;
esac
exit 0


